// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIoPUdr7BaJvVD1dmf5x8n2ISoHTFxXl8',
    appId: '1:257461961767:android:8aa73a4086498101307a02',
    messagingSenderId: '257461961767',
    projectId: 'hello-connect-14fdd',
    storageBucket: 'hello-connect-14fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvon4LMe7_EqY_xNU9hF2bncojYirOhU',
    appId: '1:257461961767:ios:41af57d9ce86dcbe307a02',
    messagingSenderId: '257461961767',
    projectId: 'hello-connect-14fdd',
    storageBucket: 'hello-connect-14fdd.appspot.com',
    iosClientId: '257461961767-395ne894irnqha3u50j663si5ufnkmlk.apps.googleusercontent.com',
    iosBundleId: 'com.child.learning.admin.panel.childappadminpanelll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvon4LMe7_EqY_xNU9hF2bncojYirOhU',
    appId: '1:257461961767:ios:41af57d9ce86dcbe307a02',
    messagingSenderId: '257461961767',
    projectId: 'hello-connect-14fdd',
    storageBucket: 'hello-connect-14fdd.appspot.com',
    iosClientId: '257461961767-395ne894irnqha3u50j663si5ufnkmlk.apps.googleusercontent.com',
    iosBundleId: 'com.child.learning.admin.panel.childappadminpanelll',
  );
}
